WIP: materialize-cssを適用した
i544c/ittern pull request #21
Opened 2017-09-08 04:27 UTC by i544c

materialize-cssを導入し、ビューを整えた。

2017-09-09 05:24 UTC, euglena1215 commented
@i544c 
semantic uiやめたんです...?

2017-09-09 11:17 UTC, euglena1215 commented on app/assets/javascripts/application.js
> +//= require jquery
@i544c 
`bundle exec rails s` したら以下のエラーを吐きました。
```
Sprockets::FileNotFound - couldn't find file 'jquery' with type 'application/javascript'
```

いままでjqueryは入れてなかったような気がするんですが、
そちらだとどこかに置いてるjqueryがきちんと読み込まれるんです？

2017-09-09 11:36 UTC, i544c commented
semantic uiには良い感じにタグ入力できるようなcomponentが無かったので、タグ入力できるcomponentが元からあるmaterialize-cssを使用しました:bow:

2017-09-09 11:47 UTC, i544c commented on app/assets/javascripts/application.js
> +//= require jquery
`bundle exec rails assets:precompile`をお願いします:pray:
jqueryはpackage.jsonにmaterialize-cssを書いたので、precompile時にnode_modulesに入ります。これは`config/initializers/assets.rb`にnode_modulesをアセットのパスに追加するように書かれているので、`require jquery`が上手いこと働くという算段、のはずです...多分。

2017-09-09 16:38 UTC, euglena1215 commented on app/assets/javascripts/application.js
> +//= require jquery
@i544c 
precompileすると下記エラーが発生したのですが、yarnのバージョンを上げると解決する系のやつですか？
```
/usr/local/Cellar/yarn/0.27.5/libexec/lib/v8-compile-cache.js:3
const Module = require('module');
^^^^^
SyntaxError: Use of const in strict mode.
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/usr/local/Cellar/yarn/0.27.5/libexec/bin/yarn.js:6:1)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
rails aborted!
Sprockets::FileNotFound: couldn't find file 'jquery' with type 'application/javascript'
```

2017-09-10 02:08 UTC, i544c commented on app/assets/javascripts/application.js
> +//= require jquery
@euglena1215 そちらのyarnはv0.27.5ですかね...
こちらの環境ではnodeがv8.4.0、yarnがv1.0.1です。多分バージョン上げれば解決するかと思われます。

2017-09-10 02:45 UTC, euglena1215 commented on app/assets/javascripts/application.js
> +//= require jquery
@i544c サーバ起動しましたー！
あとprecompileで生成させるファイルもgitに上がってる気がするのでその辺りをgitignoreに追加してほしいですー

2017-09-10 02:49 UTC, euglena1215 commented
@i544c 
これっていまWIPだからまだレビューはいいんですよね？

2017-09-11 14:45 UTC, i544c commented on app/assets/javascripts/application.js
> +//= require jquery
@euglena1215 gitignoreに含める範囲としては`public/assets/*`でよろしいでしょうか？？

2017-09-11 15:18 UTC, i544c commented
@euglena1215 issue出して、もっと細かくすべきでしたね...すみません。
とりあえず企業一覧はcssを当てたということで、そういうPRにします。

2017-09-11 15:19 UTC, i544c commented
@euglena1215 レビューお願いします:pray:

2017-09-11 15:46 UTC, euglena1215 commented on app/assets/javascripts/application.js
> +//= require jquery
@i544c 
`public/assets/*` だと影響範囲が広すぎるので `public/assets/application-*.css` みたいな感じにしてもらえるとありがたいです

2017-09-11 16:08 UTC, i544c commented on app/assets/javascripts/application.js
> +//= require jquery
@euglena1215 https://github.com/i544c/ittern/pull/21/commits/4ddb401 で致しました:pray:

2017-09-11 22:50 UTC, euglena1215 requested changes

2017-09-11 22:50 UTC, euglena1215 commented on app/controllers/companies_controller.rb
> +    # @companies = Company.all.includes(:tags)
このコメントアウトは削除してもらって大丈夫ですー

2017-09-12 00:08 UTC, euglena1215 requested changes

2017-09-12 00:08 UTC, euglena1215 commented on app/assets/javascripts/application.js
> +//= require jquery
@i544c 
他にも `application-*.js` とか `css.gz` とか色々あるっぽいんですがもしこの辺もprecompileで生成されるものならignoreに追加お願いします！
この辺りはどれがどうなのかよく把握してないので....

2017-09-13 15:12 UTC, euglena1215 approved these changes

2017-09-13 15:12 UTC, euglena1215 commented
@i544c 多分おっけーなのでマージしましょう！

2017-09-13 15:12 UTC, merged