[WIP] 体験談一覧のビューを修正
i544c/ittern pull request #26
Opened 2017-09-16 14:09 UTC by i544c

体験談一覧を良い感じに整える。
ついでにnavbarも修正。

Closes #24 #25

2017-09-17 07:36 UTC, i544c commented
@euglena1215 レビューお願いします:pray:

2017-09-17 08:49 UTC, euglena1215 requested changes

2017-09-17 08:49 UTC, euglena1215 commented on app/views/companies/_form.html.erb
> +</script>
同じ処理がreviews/_formにもあるのでpartialで切り出してもらえると！
もしくはjsファイルにまとめる？
```
+<script>
 +$("document").ready(function() {
 +  $('.chips').material_chip({
 +    placeholder: "タグ"
 +  });
 +  $('#tags input').attr('id', 'company_tag_list');
 +  $('#tags input').attr('name', 'company[tag_list]');
 +});
 +</script>
```

2017-09-17 10:35 UTC, euglena1215 commented
個人的には
* タグをタグっぽく表示してほしい
* タグを押すとタグで検索した結果が表示されてほしい
* 検索するときに一度「検索」を押さないと検索できないので、標準的な項目はあらかじめ表示させておいてその他は「詳細検索」みたいな感じにしてほしい
* dropdownは押したボタンの下ににょいっと表示されてほしい

<img width="427" alt="2017-09-17 19 12 01" src="https://user-images.githubusercontent.com/13253769/30519885-28ba7744-9bdc-11e7-8218-157a52b8d7b5.png">

体験談一覧のコンテンツはこんなイメージです(雑ですみません、、、)

<img width="753" alt="2017-09-17 19 33 45" src="https://user-images.githubusercontent.com/13253769/30519993-2bf4b9f8-9bdf-11e7-9dbb-212c9fd9d8fa.png">

検索はこんなイメージです(これも雑ですみません、、)
どれを表示させるかとかは一緒に考えたいと思ってます

2017-09-17 10:38 UTC, euglena1215 commented
@i544c 
コメントしましたー

2017-09-18 14:55 UTC, i544c commented
@euglena1215 
とりあえず今日は検索周りの見た目を修正しました～
![ittern_review_search](https://user-images.githubusercontent.com/15726229/30548244-98d82fe4-9ccc-11e7-80ad-1ce505264bac.PNG)

明日にはご指摘頂いた部分全て修正出来るかと思いますー

2017-09-19 09:00 UTC, i544c commented
@euglena1215 
経験談一覧のカードの見た目を整えましたー
![ittern_review](https://user-images.githubusercontent.com/15726229/30584321-5434ab68-9d64-11e7-8034-6f70cc3919a9.PNG)

2017-09-19 11:44 UTC, euglena1215 commented
@i544c 
すげぇ....!!!!
マージさせていただきます！！！！

2017-09-19 11:44 UTC, euglena1215 approved these changes

2017-09-19 11:44 UTC, merged