[WIP] 体験談と企業の詳細画面を整える
i544c/ittern pull request #29
Opened 2017-09-20 15:44 UTC by i544c

これでrelease行けるかな？？

Closes #25 #28

2017-09-21 04:57 UTC, i544c commented
@euglena1215 
取り急ぎ、経験談と企業の詳細画面を整えました。
ただ経験談詳細画面のレイアウトがパッとしないので、何か良い案があったらお願いします:pray:
![ittern_review_show](https://user-images.githubusercontent.com/15726229/30679463-b692c102-9ed4-11e7-9d36-47446e5e262c.PNG)

2017-09-22 05:53 UTC, euglena1215 commented
@i544c 
<img width="714" alt="2017-09-22 14 49 47" src="https://user-images.githubusercontent.com/13253769/30730935-68479e74-9fa5-11e7-90b3-79ff63ddb4da.png">

例えばこんな感じとかどうでしょうか？
メインとなるのは体験談なのでこうすれば体験談に目がいきやすいんじゃないかなと思いました
日給をどこに表示させるかが思いつかなかったのでよしなにやってくれるとありがたいです...

2017-09-22 06:00 UTC, euglena1215 requested changes

2017-09-22 06:00 UTC, euglena1215 commented on app/views/reviews/index.html.erb
> +    <%= f.select :rate_gteq, (1..5).to_a, include_blank: Review.human_attribute_name('rate') %>以上
全然対応してなくてすみません...
ありがとうございます🙏

2017-09-22 06:00 UTC, euglena1215 commented on app/views/reviews/index.html.erb
> +  <b><%= @reviews.count %>件</b>
`count` はSELECT COUNT(*)のようなクエリを発行するので`length`か`size`を使ってください。

`length`は単純に要素数を返すメソッドで
`size`は状況に応じて要素数を返したりクエリを発行したりするメソッドです。
とりあえず`size`使っとけばいい感じにしてくれるかなって思います

2017-09-22 06:01 UTC, euglena1215 commented on app/views/reviews/index.html.erb
> +    <%= f.select :rate_gteq, (1..5).to_a, include_blank: Review.human_attribute_name('rate') %>以上
全然対応してなくてすみません...
ありがとうございます🙏

2017-09-26 10:43 UTC, i544c commented
@euglena1215 
全然手を付けてなくてすみません...
レイアウト案、ありがとうございますm(_ _)m

レビューお願いします:pray:
![ittern_review_show_icon](https://user-images.githubusercontent.com/15726229/30856279-d47816be-a2f2-11e7-9f2d-cea2be37aa7a.PNG)

2017-09-26 15:50 UTC, euglena1215 approved these changes

2017-09-26 15:59 UTC, euglena1215 commented
@i544c 
再現してもらってありがとうございます！
マージしますー

2017-09-26 15:59 UTC, merged